/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("me.champeau.jmh") version "0.7.2"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.openjdk.jmh.jmh.core)
    api(libs.org.openjdk.jmh.jmh.generator.annprocess)
    testImplementation(libs.junit.junit)


    annotationProcessor("org.openjdk.jmh:jmh-generator-annprocess:1.35")
    // this is the line that solves the missing /META-INF/BenchmarkList error
    //jmhAnnotationProcessor 'org.openjdk.jmh:jmh-generator-annprocess:1.36'
}

group = "one.util"
version = "ggr"
description = "StreamEx"
java.sourceCompatibility = JavaVersion.VERSION_1_8

java {
    withSourcesJar()
    withJavadocJar()
}

tasks {
    jmh {
        // Additional configurations for the JMH task if needed
        fork = 1
        warmupIterations = 5
        iterations = 10
    }
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
